import Head from 'next/head'
import {NavTop} from '../components/landing/NavTop'
import {PricingSection} from '../components/landing/sections/pricing/Pricing'
import {PricingContentRemote} from '../interfaces/pricing'
import {pricing} from '../data/pricing'
import {FeaturesSection} from '../components/landing/sections/features/Features'
import {ReviewsSection} from '../components/landing/sections/reviews/Reviews'
import {features} from '../data/features'
import {Feature} from '../interfaces/feature'
import {PricingSectionWave} from '../components/utils/waves/PricingSection'
import {PricingSectionPebbles} from '../components/utils/svg/PricingSectionPebbles'

interface LandingProps {
  pricingSectionData: PricingContentRemote[];
  featuresSectionData: Feature[]
}

export async function getStaticProps() {
  // data should be remote
  const pricingSectionData = pricing
  const featuresSectionData = features

  return {
    props: {pricingSectionData, featuresSectionData},
  }
}

const Landing = ({pricingSectionData, featuresSectionData}: LandingProps) => <>
  <Head>
    <title>Cryptohopper</title>
    <meta name="description" content="Generated by create next app"/>
    <link rel="icon" href="/favicon.ico"/>
  </Head>

  <div className={'z-0'}>
    <div className={'absolute top-[441px] z-0'}>
      <PricingSectionWave/>
    </div>

    <div className={'absolute top-[400px] left-[400px] z-0'}>
      <PricingSectionPebbles/>
    </div>
  </div>

  <div className={'flex flex-col z-10'}>
    <div className={'flex justify-center'}>
      <div className={'w-[1520px]'}>
        <NavTop/>
        <div className={'flex flex-col items-center'}>
          <div className={'h-[143px]'}/>
          <PricingSection data={pricingSectionData}/>
          <div className={'h-[173px]'}/>
          <FeaturesSection data={featuresSectionData}/>
        </div>
        <div className={'h-[80px]'}/>
      </div>
    </div>
    <div className={'w-auto flex justify-center'} style={{backgroundColor: '#F7FDFD'}}>
      <div className={'w-[1520px] flex flex-col items-center'}>
        <div className={'h-[150px]'}/>
        <ReviewsSection/>
        <div className={'h-[290px]'}/>
      </div>
    </div>
    <div className={'h-[1000px]'}/>
  </div>
</>

export default Landing
