import Head from 'next/head'
import {NavTop} from '../components/landing/NavTop'
import {FeaturesTitle} from '../components/landing/sections/features/FeaturesTitle'
import {FeaturesDropdown} from '../components/landing/sections/features/FeaturesDropdown'
import {PricingSection} from '../components/landing/sections/pricing/Pricing'
import {PricingOptions} from '../enums'
import {PricingContentRemote} from '../interfaces/pricing'
import {pricing} from '../data/pricing'

interface LandingProps {
  pricingSectionData: Record<PricingOptions, PricingContentRemote>
}

export async function getStaticProps() {
  // data should be remote
  const pricingSectionData = pricing

  return {
    props: {pricingSectionData},
  }
}

const Landing = ({pricingSectionData}: LandingProps) => (
  <div className={'flex justify-center'}>
    <div className={'w-[1920px]'}>
      <Head>
        <title>Cryptohopper</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link href="http://fonts.cdnfonts.com/css/sofia-pro" rel="stylesheet"/>
      </Head>

      <NavTop/>
      <div className={'flex flex-col items-center'}>
        <div className={'h-[143px]'}/>
        <PricingSection data={Object.values(pricingSectionData)}/>
        <div className={'h-[173px]'}/>
        <FeaturesTitle/>
        <div className={'h-[37px]'}/>
        <FeaturesDropdown/>
      </div>
      <div className={'h-[1000px]'}/>
    </div>
  </div>
)

export default Landing
